---
version: "3.8"
services:
  pyrmqtt:
    build: .
    # ⚠️ Change host, username and password details to match your environment
    command: --host 10.0.0.1 --username username --password password --device /serial
    devices:
      # ⚠️ Change /dev/ttyUSB0 to where your raven dongle is mounted
      - "/dev/ttyUSB0:/serial"
      - "/serial"
    image: pyrmqtt
    container_name: pyrmqtt
    restart: always
    tty: true
